name: whatsapp_flutter_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.24.0
  firebase_auth: 4.15.0
  cloud_firestore: 4.13.3
  firebase_storage: 11.5.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/backgroundImage.png
  uses-material-design: true

