// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMsKflW_TXA_dTQEScxtoM3hlmyoDijc',
    appId: '1:418831035080:web:3b1523360ec97a989913fd',
    messagingSenderId: '418831035080',
    projectId: 'whatsapp-backend-3466f',
    authDomain: 'whatsapp-backend-3466f.firebaseapp.com',
    storageBucket: 'whatsapp-backend-3466f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvB3kVQ1ReA2OlbdRZfLpTz4O4-nzZh2A',
    appId: '1:418831035080:android:ec35867a956a45599913fd',
    messagingSenderId: '418831035080',
    projectId: 'whatsapp-backend-3466f',
    storageBucket: 'whatsapp-backend-3466f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ3DJPJttBd-uxNDaBA5ixH7MpVKQ7AHI',
    appId: '1:418831035080:ios:7a6fbb3eb6e52eca9913fd',
    messagingSenderId: '418831035080',
    projectId: 'whatsapp-backend-3466f',
    storageBucket: 'whatsapp-backend-3466f.appspot.com',
    iosBundleId: 'com.example.whatsappFlutterFirebase',
  );
}
